name: doora_app
description: DooraBag - Home services app
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

# Android में versionCode/versionName यहीं से auto उठेंगे
version: 1.0.3+4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  google_maps_flutter: ^2.7.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  webview_flutter: ^4.13.0
  go_router: ^16.2.4
  lottie: ^2.7.0
  video_player: ^2.9.1
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2 
  provider: ^6.1.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/app_logo.svg
    - assets/images/
    - assets/banners/
    - assets/cards/
    - assets/anim/
    - assets/video/washing_machine_1.mp4
    - assets/video/washing_machine_2.mp4
    - assets/video/ac_servicing.mp4
    - assets/photos/
    - assets/brands/brands_wall.png
    - assets/logo/app_icon.png
    - assets/photos/chimney repair.webp
    - assets/icons/geyser installation.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"